# Simplified OpenTelemetry Collector Configuration for CIRISLens

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    
  otlp/tempo:
    endpoint: cirislens-tempo:4317
    tls:
      insecure: true
      
  prometheusremotewrite:
    endpoint: http://cirislens-prometheus:9090/api/v1/write
    
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]
      
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, prometheusremotewrite]
      
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]