# Tempo Configuration for CIRISLens
# Distributed tracing backend

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:9095

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 336h  # 14 days default
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

limits_config:
  max_traces_per_user: 100000
  max_bytes_per_trace: 5000000
  max_search_bytes_per_trace: 50000
  max_bytes_per_tag_values_query: 5000000
  ingestion_rate_limit_bytes: 15000000
  ingestion_burst_size_bytes: 20000000

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
      storage:
        remote_write:
          - url: http://mimir:9009/api/v1/push
            headers:
              X-Scope-OrgID: ciris